[pytest]
addopts = -p no:cacheprovider
testpaths = tests
filterwarnings =
    ignore:Setting the shape on a NumPy array has been deprecated:DeprecationWarning
    ignore::matplotlib.MatplotlibDeprecationWarning
